const usersData = [
    {
        id: 1,
        name: 'John Doe',
        email: 'john.doe@example.com',
        dateOfReg: '2021-09-25',
        lastLogin: '2023-10-05',
        status: 'Active',
    },
    {
        id: 2,
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        dateOfReg: '2022-01-15',
        lastLogin: '2023-09-28',
        status: 'Inactive',
    },
    {
        id: 3,
        name: 'Michael Johnson',
        email: 'michael.johnson@example.com',
        dateOfReg: '2020-12-08',
        lastLogin: '2023-10-01',
        status: 'Pending',
    },
    {
        id: 4,
        name: 'Emily Williams',
        email: 'emily.williams@example.com',
        dateOfReg: '2021-06-17',
        lastLogin: '2023-10-03',
        status: 'Active',
    },
    {
        id: 5,
        name: 'Daenerys Targaryen',
        email: 'daenerys.targaryen@example.com',
        dateOfReg: '2019-11-30',
        lastLogin: '2023-09-25',
        status: 'Pending',
    },
    {
        id: 6,
        name: 'Melisandre',
        email: 'melisandre@example.com',
        dateOfReg: '2018-05-12',
        lastLogin: '2023-10-02',
        status: 'Active',
    },
    {
        id: 7,
        name: 'Ferrara Clifford',
        email: 'ferrara.clifford@example.com',
        dateOfReg: '2022-04-09',
        lastLogin: '2023-09-29',
        status: 'Active',
    },
    {
        id: 8,
        name: 'Rossini Frances',
        email: 'rossini.frances@example.com',
        dateOfReg: '2021-08-03',
        lastLogin: '2023-09-30',
        status: 'Inactive',
    },
    {
        id: 9,
        name: 'Harvey Roxie',
        email: 'harvey.roxie@example.com',
        dateOfReg: '2020-02-19',
        lastLogin: '2023-10-04',
        status: 'Active',
    },
];

export default usersData;
